### ISSUE TITLE
Add class-diagram.svg

### ISSUE THREAD

**Issue by peterdesmet** [gbif/doc-camera-trap-guide#13]
Use diagrams.net to create class-diagram. See https://github.com/gbif/doc-camera-trap-guide/issues/7#issuecomment-1587276795, which refers to the [eDNA guide README](https://github.com/gbif/doc-publishing-dna-derived-data#diagrams) for guidance.

Source file:

![class-hierarchy-grouped](https://github.com/gbif/doc-camera-trap-guide/assets/600993/7f05684d-8e29-40b7-bce8-b4d84ba95a45)

**Comment by peterdesmet** [comment]
@pietrH would you be willing to tackle this?

**Comment by PietrH** [comment]
I left some comments about this in an email + the google doc. 

![camtrap_model_classes](https://github.com/gbif/doc-camera-trap-guide/assets/48065851/838d554d-eb48-427e-8049-baa8448ab15c)

**Comment by PietrH** [comment]
In mermaid: 


```mermaid
erDiagram
    Organisation}o--|{Participant : ""
    Organisation||--|{Project : ""
    Project}o--|{Participant : ""
    Project ||..o{Subproject : ""
    Subproject||..|{Deployment : ""
    Project ||--|{Deployment : ""
    Deployment}|..|{"Deployment Group" : ""
    Deployment||--||Location : ""
    Deployment}|--|{Camera : ""
    Deployment||--o{Media : ""
    Camera}|..|{"Media Type" : ""
    "Media Type"||..|{Media : ""
    Media}|..o{Sequence : ""
    Sequence||..o{Observation : ""
    Media|o--o{Observation : ""
    Observation}|..||"Observation Type" : ""
```

I used https://mermaid.live/

**Comment by PietrH** [comment]
Remade the diagram, embedded below, you should be able to open this svg in diagrams.net directly:

![camtrap_model_classes_radial drawio](https://github.com/gbif/doc-camera-trap-guide/assets/48065851/57969152-96f9-423a-adfa-6eebbb2b0729)



I'll upload a copy to the drive as well. 

Link: https://drive.google.com/file/d/1FYokWMZw4IItGWp1bRNie6pTPOn30w90/view?usp=sharing

xml: https://gist.github.com/PietrH/e822623f9c618e321eff5b54449b9cbd

I tried using diagonals, but the crow feet don't allign nicely out of the box in diagrams.net, could probably be done with some finagling:

![image](https://github.com/gbif/doc-camera-trap-guide/assets/48065851/8c31df51-a310-4796-a6c1-5460d3bbbb21)
