### ISSUE TITLE
index inclusions

### ISSUE THREAD

**Issue by kcopas** [gbif/doc-camera-trap-guide#15]
In adding the cover illustrations, I noticed a few dozen lines of term/citation references in index.en.adoc. Not sure they belong there, as that index isn't an index of terms but a index for building the AsciiDoc document. Not urgent, by any means, but just flagging it here and now before I forget.

**Comment by peterdesmet** [comment]
Hi Kyle, do you mean this:

https://github.com/gbif/doc-camera-trap-guide/blob/97f38058e65230b9213434577b87233c7cf8c4e1/index.en.adoc?plain=1#L21-L127

That is a list of short codes for (term) URLs. By defining them in index.en.adoc, we can use the syntax:

> Terms like {deployments-deploymentID} or term:dwc[dwc:occurrenceID] expect an identifier that is:

To refer to a term without always having to repeat the URL (which is prone to error). They render as:

<img width="685" alt="Screenshot 2023-11-13 at 16 31 35" src="https://github.com/gbif/doc-camera-trap-guide/assets/600993/abbdcb68-50bb-468d-82f1-8fc994fcdda1">

---

I defined all those short codes in index.en.adoc based on advise by @MattBlissett, but if you think they are better defined elsewhere (e.g. separated file), let me know.

**Comment by kcopas** [comment]
Thanks for the clarification @peterdesmet. I think I was flagging something I didn't understand. The rationale sounds reasonable to me (thanks @MattBlissett ), so as long as it works, I'm fine with it.
