### ISSUE TITLE
Update colophon

### ISSUE THREAD

**Issue by peterdesmet** [gbif/doc-camera-trap-guide#16]
https://github.com/gbif/doc-camera-trap-guide/blob/1.0/colophon.en.adoc

- [x] Authors
- [x] Contributors
- [x] Citation
- [x] DOI
- [x] Version
- [x] Update title in https://github.com/gbif/doc-camera-trap-guide/blob/1.0/README.adoc

**Comment by LienReyserhove** [comment]
Almost done, waiting for the DOI

**Comment by peterdesmet** [comment]
The header of the document still says:

> Author One communication@gbif.org Author Two Version 5b2041e, 2023-08-25 15:23:39 UTC

How can Author One and Two be updated?

**Comment by MattBlissett** [comment]
Line 2 of index.en.adoc.

The version is also set there, by :revnumber: and :revdate: — they can just be "1" and "August 2023" or whatever is appropriate, they don't need to be generated from the Git parameters.

**Comment by laurarussell** [comment]
added doi to colophone

**Comment by peterdesmet** [comment]
Hi @laurarussell when will the DOI resolve (currently does not)? https://doi.org/10.35035/doc-7ssq-vm94

**Comment by laurarussell** [comment]
@peterdesmet when we make the production release for the Community Review. Likely tomorrow or Friday. We don't want the DOI to go to UAT (correct @kcopas?)
