### ISSUE TITLE
Remove Appendix A

### ISSUE THREAD

**Issue by peterdesmet** [gbif/doc-camera-trap-guide#19]

**Comment by LienReyserhove** [comment]
https://github.com/gbif/doc-camera-trap-guide/commit/fcc2e2de0e255b6b15cf8ad645a0e6c92bafbad1

**Comment by peterdesmet** [comment]
I think the reference in https://github.com/gbif/doc-camera-trap-guide/blob/1.0/index.en.adoc#L154 should probably also be removed.

**Comment by LienReyserhove** [comment]
Done, see https://github.com/gbif/doc-camera-trap-guide/commit/d79e905c5d16955fa3393126c3d6785edd105b53
