### ISSUE TITLE
Run spellcheck

### ISSUE THREAD

**Issue by peterdesmet** [gbif/doc-camera-trap-guide#20]

**Comment by MattBlissett** [comment]
Note the build output runs a basic spell check with the GBIF (UN, Oxford English) dictionary: https://builds.gbif.org/job/doc-camera-trap-guide/lastBuild/console

It does report identifiers and bits of syntax though.

**Comment by peterdesmet** [comment]
All the words listed by the spell check:

accessuri (5): anchor
accessURI (6): term
agouti (5): anchor
Agouti (10): term
alba (1): sciname
alces (1): sciname
Alces (1): sciname
alony (1): ref
amatulli (1): ref
**AmphBIO (1): corrected to AmphiBIO**
**analyzing (1): corrected to analysing**
Anas (11): sciname
Anatidae (2): sciname
**anomyze (1): corrected to anonymize**
**anonymize (1): considered ok**
**anonymized (3): considered ok**
Ardea (7): sciname
**authorative (2): considered ok**
AVONET (1): name
baitUse (2): term
basisofrecord (2): anchor
**behavior (7): considered ok, all refer to the Darwin Core term**
bennett (1): ref
berkel (1): ref
bibliographicCitation (1): term
**Biomes (1): is ok**
boven (1): example value
bradley (1): ref
bubnicki (2): ref
buchhorn (1): ref
burton (2): ref
cadman (2): ref
**camelCase (1): corrected to camel case**
camelot (4): ref
camerabase (1): ref
cameraDelay (1): term
cameraHeading (1): term
cameraHeight (1): term
cameraModel (1): term
cameraSetupType (1): term
cameraTilt (1): term
Campine (2): example value
camtrap (11): anchor
Camtrap (86): name
camtraptor (2): anchor
canadensis (1): sciname
capreolus (1): sciname
Capreolus (1): sciname
capturedevice (2): anchor
captureDevice (3): term
captureMethod (1): term
caravaggi (1): ref
Cervus (1): sciname
chapman (10): ref
cinerea (6): sciname
citenp (23): ref syntax
classificationMethod (1): term
classificationProbability (1): term
classificationTimestamp (1): term
classifiedBy (2): term
clements (1): ref
collectioncode (2): anchor
ContactPerson (1): term
coordinateprecision (2): anchor
coordinatesLongitude (1): example value
coordinateUncertainty (3): term
coordinateuncertaintyinmeters (2): anchor
**covariates (11): considered ok**
**Covariates (2): considered ok**
createdate (2): anchor
CreateDate (3): term
ctms (2): anchor
CTMS (2): name
cusack (2): ref
dadf (1): example value
darwin (14): anchor
datacite (1): anchor
**Datacite (1): corrected to DataCite**
DataCollector (1): term
DataCurator (1): term
datageneralizations (2): anchor
dataGeneralizations (4): term
DataManager (1): term
datasetid (3): anchor
datasetname (3): anchor
dateidentified (2): anchor
dateIdentified (3): term
**datetime (7): no guidance, but corrected to date-time**
DDTHH (3): example value
deaed (9): example value
decimallatitude (6): anchor
decimallongitude (6): anchor
delisle (1): ref
deploymentComments (2): term
deploymentEnd (1): term
deploymentGroups (1): term
deploymentID (3): term
deploymentLocation (1): term
deploymentStart (1): term
deploymentTags (1): term
Desmet (5): example value
detectionDistance (1): term
Digivol (1): name
dinerstein (1): ref
DoeDat (1): name
**ecoregions (1): considered ok**
**ectothermic (1): considered ok**
eecd (1): example value
efbcb (8): example value
EltonTraits (1): name
emammal (1): anchor
eMammal (1): name
eunis (1): anchor
eventdate (4): anchor
eventEnd (3): term
eventid (4): anchor
eventremarks (3): anchor
eventStart (4): term
eventType (1): term
exif (2): anchor
**Exif (1): corrected to EXIF**
EXIF (9): name
exifData (1): term
favorite (1): anchor
featureType (2): term
fegraus (1): ref
**fiel (1): corrected to file**
fileMediatype (2): term
fileName (1): term
filePath (3): term
filePublic (2): term
**findability (1): considered ok**
Flickr (1): name
forston (1): ref
**fossorial (1): considered ok**
GCHS (2): example value
geodeticdatum (2): anchor
**GlobTerm (1): corrected to GlobTherm**
gloverkapfer (1): ref
gomez (1): ref
guillera (3): ref
HHMMSS (1): example value
hobbs (3): ref
**hotlinking (1): corrected to hot-linking**
howe (1): ref
hsing (1): ref
http (6): part of url
https (6): part of url
Huybrechts (1): name
HYPERFIRE (1): example value
**identfier (1): corrected to identifier**
identificationremarks (2): anchor
identificationRemarks (3): term
identifiedby (3): anchor
individualcount (2): anchor
individualID (1): term
informationWithheld (1): term
iucn (1): anchor
jones (1): ref
jpeg (4): extension
jung (1): ref
kays (1): ref
kolowski (1): ref
kucera (1): ref
lamelas (1): ref
lifeStage (4): term
locationid (2): anchor
locationName (2): term
mackenzie (3): ref
**Mammalogists (1): considered ok**
MammalWeb (1): name
mcintyre (1): ref
mediaComments (1): term
mediaID (3): term
Milotic (1): name
MovingImage (2): term
mpeg (1): extension
newkirk (4): ref
nguyen (1): ref
Noëlla (1): name
**nontarget (1): corrected to non-target**
norouzzadeh (2): ref
obrien (3): ref
observationComments (1): term
observationID (3): term
observationType (1): term
occurrenceid (7): anchor
**occurrenceIDs (1): corrected to occurrenceID**
occurrenceremarks (3): anchor
occurrenceRemarks (5): term
occurrencestatus (2): anchor
oconnell (1): ref
oconnor (1): ref
oliveira (1): ref
organismid (2): anchor
PanTHERIA (1): name
parenteventid (2): anchor
PhotoTypeIdentifiedBy (1): term
Pieter (1): name
platyrhynchos (11): sciname
**possiblity (1): corrected to possibility**
**preferrably (2): corrected to preferably**
**preprocessed (1): considered ok**
**preprocessing (2): considered ok**
principalInvestigator (1): term
PrincipalInvestigator (1): term
processiepark (2): example value
ProjectContact (1): term
ProjectLeader (1): term
ProjectManager (1): term
ProjectMember (1): term
**pyroelectric (1): considered ok**
README (1): example value
Reconyx (8): name
RECONYX (1): example value
resourcecreationtechnique (2): anchor
resourceCreationTechnique (2): term
Reyserhove (2): name
rightsholder (2): anchor
rightsHolder (4): term
RightsHolder (1): term
riley (1): ref
risc (3): ref
robertson (1): ref
Rodentia (1): sciname
rovero (6): ref
rowcliffe (4): ref
samplingDesign (1): term
samplingeffort (3): anchor
samplingprotocol (2): anchor
scientificname (5): anchor
scrofa (2): sciname
sequenceIdentifiedBy (1): term
serviceexpectation (2): anchor
serviceExpectation (2): term
setupBy (1): term
shannon (3): ref
simpson (1): ref
Siras (1): name
sollmann (1): ref
soria (1): ref
sRGB (1): example value
**standardised (1): corrected to standardized**
StillImage (4): term
stroom (1): example value
**subadult (1): considered ok**
**subproject (8): considered ok**
**subprojects (2): considered ok**
**Subprojects (1): considered ok**
sunarto (2): ref
swanson (2): ref
Tanja (1): name
taxonid (2): anchor
**taxonomical (1): considered ok**
**techniqually (1): corrected to technically**
**timeframe (1): corrected to time frame**
**timelapse (1): corrected to time lapse**
tobias (1): ref
tobler (3): ref
**typicall (1): corrected to typically**
**unselective (1): considered ok**
**verifing (1): corrected to verifying**
videoFile (1): example value
Wageningen (1): name
waller (1): ref
wearn (11): ref
weinstein (1): ref
**whitespace (2): corrected to white space**
wieczorek (6): ref
wildcam (1): anchor
wildtrax (3): anchor
**Wildtrax (3): corrected to WildTrax**
WildTrax (1): name
wilkinson (3): ref
wilman (1): ref
yousif (1): ref
zhao (1): ref
