### ISSUE TITLE
Merge cells in Table 1

### ISSUE THREAD

**Issue by LienReyserhove** [gbif/doc-camera-trap-guide#22]
Ideally, the key references in [table 1](https://docs.gbif-uat.org/camera-trap-guide/en/#table-aims) should be merged for `Study Aim`= `diversity`. This means that `Tobler et al. (2008); Cusack et al. (2015)` applies to the outputs `richness`, `diversity indices` and `beta diversity`. How to do this?

**Comment by peterdesmet** [comment]
Fixed in 3f1d01b.
