### ISSUE TITLE
2.1 What are camera traps

### ISSUE THREAD

**Issue by dhobern** [gbif/doc-camera-trap-guide#28]
In section 2.1, it would be good to consider the following:

1. The current definition focuses on trail cams - this is perfectly reasonable and may make the document easier for users of such cameras to understand and interpret, although I would suggest including "trail cameras" in parentheses somewhere in this paragraph (in addition to the glossary reference) to make this clear to people who use that common term.
2. However, growing numbers of people (myself included) are exploring use of other camera types to try to standardise biodiversity monitoring. In my case, it's a Raspberry Pi using motion detection (but no PIR) to image insects attracted to light at night. This shares almost all the characteristics included in your definition - including such examples here, but explaining any ways that the rest of the guide may be less relevant, would assist those who are considering such use cases.
3. It may be worth explaining that camera traps as described here are also a subset of the devices that produce MachineObservations and to place that in context. You later tell users to assign MachineObservation to their occurrence records, but in my experience this confuses some people, particularly if humans are providing the identifications for the detections. You later refer to Human or Machine classification, so this seems a useful place to draw the distinctions between HumanObservations (where a human is actively in control of the decision whether to record an organism) and MachineObservations (where a machine responds to a sensor to collect each observation) and between "human classification" (where someone goes through the images and assigns identifications) and "machine classification" where a machine uses ML or some other algorithm to classify the detections. 
4. It might even be worth pointing out that the value of camera traps comes partly because they remove uncertainty associated with human judgment. If a user cherrypicks a subset of detections and only published those that interest them, you could make a case that we are then talking about HumanObservations. (Filtering based on choices documented in the metadata is different, e.g. if the protocol is only to record Felidae or only to record the timestamp for the first observation each night of each species - in these cases, we are talking about MachineObservations for "cats" or "first appearance of X" - see also your table 1.)
5. Maybe contextualise camera traps alongside e.g. drone imagery and ecoacoustics to explain how other MachineObservations may differ and what aspects are common. Ecoacoustic detection of individual animals is particularly close.
6. You exclude timelapse detections. This seems a little arbitrary. Even PIR-triggered cameras have built-in delays that limit frequency. In my insect case, I'm pretty sure that 10-second timelapse gives me almost all species detections I get with motion detection but leaves me with 2,160 images over six hours rather than 12,000+ from motion detection on most nights and also allows for reduced power consumption. Timelapse may also be better for deriving sample event metrics because it gives a more consistent set of sensed observations to process. Perhaps explain how timelapse fails the intention of this document.

Having written all that, I wonder whether what I am really looking for is not some edits to section 2.1 but a new section explaining the concepts behind machine observations.

**Comment by peterdesmet** [comment]
Thanks for the feedback Donald! I agree that limiting to PIR (and thus excluding time lapse) is too restrictive. Both are supported in Camtrap DP. Placing camera traps in a broader context of camera and Machine Observations (and explaining what those are) would be good indeed.

**Comment by peterdesmet** [comment]
Todo:

- [x] Mention the guide has a focus on trail cameras, but practices (and Camtrap DP) can be used for other types.
- [x] Place camera traps in broader perspective of MachineObservations (point 3, 4, 5), and their characteristics (less bias, etc.)
- [x] Mention trail cameras in 2.1
- [x] Add trail camera to glossary: already done as synonym for [camera](https://docs.gbif-uat.org/camera-trap-guide/en/#camera).

**Comment by peterdesmet** [comment]
@dhobern we've made the following changes based on your input in this issue. I'll close this issue, but we can open it again if you think something should be addressed still.

[Target audience](https://docs.gbif-uat.org/camera-trap-guide/en/#section-target-audience) now mentions the following (we opted to use "traditional camera trap" over "trail camera"):

> The authors of this guide have experience with traditional camera traps (designed for medium-to-large-sized terrestrial mammals), but many of the recommendations, as well as the [Camtrap DP](https://docs.gbif-uat.org/camera-trap-guide/en/#camtrap-dp) standard, should be applicable to data from other types of camera traps.

[Section 2.1](https://docs.gbif-uat.org/camera-trap-guide/en/#section-what-are-camera-traps) now mentions several of the words you indicated were missing (emphasis mine):

> Camera traps are recording devices that are deployed in the field to automatically capture images or videos of wildlife activity. They are also known as game cameras, **trail cameras** or scouting cameras. They can record media at a regular interval (**time lapse**) or when triggered by the activity of an animal. Traditionally, camera traps refer to those designed to record medium-to-large-sized terrestrial mammals with a passive infrared (PIR) [sensor](https://docs.gbif-uat.org/camera-trap-guide/en/#sensor) ([Hobbs and Brehme 2017](https://docs.gbif-uat.org/camera-trap-guide/en/#hobbs-2017)), but other types exist for e.g. the marine environment or **insects**. Just like satellites, drones, GPS trackers or **acoustic sensors**, camera traps collect **machine observations**. Acoustic sensors in particular are quite similar to camera traps, using audio rather than image/video to monitor the surrounding ecosystem. All these technologies have the benefit that they can collect data at a scale and frequency that would be challenging to obtain through human observations, and typically **suffer less from human bias, interpretation or interference**.

[Section 3.5.1 Classification](https://docs.gbif-uat.org/camera-trap-guide/en/#section-classification) now mentions:

> Classification can be done by humans and/or machines.

[basisOfRecord](https://docs.gbif-uat.org/camera-trap-guide/en/#section-basisofrecord) (this seemed like the best section to elaborate this, in addition to section 2.1) now mentions:

> The specific nature of the record. Set to `MachineObservation` for all records. While humans decide when and were to deploy a camera trap, and humans or machines (AI) can [classify](https://docs.gbif-uat.org/camera-trap-guide/en/#classification) media, the capturing of the record is done by a machine responding to a sensor. This is critically different from human observations, where a human is actively in control of the decision whether to record an organism or not.
