### ISSUE TITLE
FAIR data

### ISSUE THREAD

**Issue by dhobern** [gbif/doc-camera-trap-guide#29]
I'd recommend a fuller explanation of the concepts behind FAIR somewhere near the start of the document. This gives context for why many of the recommendations make a real difference. As far as I can see, the only explanation of how FAIR relates to these data is "The best way to do this is by depositing your data in a data repository" on page 24.

Publishing to a repository and using the GBIF network to publish data covers the F and the A of FAIR, but this document implicitly is a response to how to achieve the I and the R. 

Here are my suggestions on what to include (in a section entitled "FAIR data from camera traps" or similar:

1. Explain in real-world terms why everyone is focusing on FAIR data. This is about ensuring that both humans and machines are able to make the best possible (and most appropriate) use of valuable data now and on into the future. Being able to find and get the data is the start. The hard part is making sure that the data are not open to misinterpretation (or difficult/impossible to interpret).
2. In the context of camera traps, this means we should _ideally_ aim for the combination of our metadata and data reliably to communicate:
   * Details of the trap and its placement
   * How the trap was triggered (PIR, purely visual motion detection, [timelapse], etc.)
   * Schedules (only after 21:00 and before 03:00 or whatever)
   * Any subsequent filtering of the images prior to classification
   * Any post-processing (e.g. CV to detect objects of interest)
   * Scope for records: what detectable event/features are recorded as observations (all images, all mammals captured in images, all cats, summary count of individuals per time period, etc.) - the dataset should include every instance of this event/feature
   * Source of identifications/classification (single human expert, crowd-sourced, ML model, etc.)
   * Outages and other unplanned events
3. If all these elements are recorded in a way that a human can understand, we make it possible for them to determine whether the data are fit for purpose for their study (or can be mapped into a suitable form).
4. If all these elements are recorded in a way that a machine can interpret (reliable use of identifiers, vocabularies, ontologies, etc.), these data could be useful in unsupervised/semi-supervised modeling and decision-support tools.
5. Perfection should not be the enemy of the good. Most datasets are imperfect, and it is hard to include all this information, but at least considering these questions gives the opportunity to maximise the long-term benefit delivered by the original study.

Obviously, most of the document is about use of relevant standards and implicitly addresses these issues, but an up-front exploration may help users to see why each point matters.

**Comment by peterdesmet** [comment]
We have been contemplating including a section on FAIR (and didn’t because there are already many good explanations out there), but you raise good points in having a section explaining FAIR in _the context of camera trap data._

**Comment by peterdesmet** [comment]
Discussed with @LienReyserhove 

- Probably a section on FAIR is best place at the start of chapter 4 (Publishing camera trap data)
- Include points mentioned by @dhobern above
- The section "Is Camtrap DP FAIR?" can be of inspiration: https://doi.org/10.32942/X2BC8J

**Comment by peterdesmet** [comment]
@dhobern we've made the following changes based on your input in this issue:

- There is a new section [4.1 Fair camera trap data](https://docs.gbif-uat.org/camera-trap-guide/en/#section-fair-camera-trap-data) that explains the four FAIR principles and how depositing at GBIF and using Camtrap DP addresses many of these for camera trap data
- The section [Project metadata](https://docs.gbif-uat.org/camera-trap-guide/en/#section-project-metadata) has been expended with more examples of what to record as part of the metadata. I think this section was a better fit for this information than the FAIR section. It also mentions that perfection should not be the enemy of good. 

I'll close this issue, but we can open it again if you think something should be addressed still.
