### ISSUE TITLE
Style bibliography

### ISSUE THREAD

**Issue by peterdesmet** [gbif/doc-camera-trap-guide#3]
- [x] Add DOIs and URLs where missing
- [x] Use the Pensoft style for the full reference
- [x] Order references alphabetically
- [x] Remove empty line between references (so it becomes a regular list)
- [x] Use `*` instead of `-`

**Comment by MattBlissett** [comment]
The style is now controlled with the BibTeX plugin, but the references need converting to BibTeX format. (Often easiest with a "download citation" button on the article website.)

**Comment by peterdesmet** [comment]
Thanks! Closing this in favour of #12.
