### ISSUE TITLE
Spelling: Media or event-based classification

### ISSUE THREAD

**Issue by peterdesmet** [gbif/doc-camera-trap-guide#32]
```
event-based classification
```

is a compound modifier and should be [written with a hyphen](https://www.grammarly.com/blog/hyphen/). This (and other) compound modifiers should be corrected in the text.

I'm not sure if we should write:

```
Media or event-based classification
Media- or event-based classification
```

@kcopas ?

**Comment by kcopas** [comment]
If I'm reading the specific question right and it's a thing in itself like event-based classification (e.g. `Media-based classification`), then `Media- or event-based classification` would be the preferred option.
