### ISSUE TITLE
section 3.4.1 (column naming): expand example of handling units

### ISSUE THREAD

**Issue by sformel-usgs** [gbif/doc-camera-trap-guide#35]
Section 3.4.1 says:

> Deployment information is best recorded in a [data management system](https://docs.gbif-uat.org/camera-trap-guide/en/index.en.html#data-management-system). If you manage your deployment information elsewhere (e.g. a spreadsheet), then we recommend the following column naming conventions: ... 
> 
> ...Avoid including units and data types. Describe these elsewhere (e.g. in a separate sheet, README document or [Table Schema](https://specs.frictionlessdata.io/table-schema/)), together with the column definition and controlled values.
> 

But then only gives an example of "bad", and not one for "good".  This is important because this section appears to target users who might not be as data management savvy (managing data in a spreadsheet) as others.  I can imagine that the linked example of Table Schema could be a little abstract and overwhelming to such a user.  

If a "good" example, including a README document could be presented, it would give a template for users who might struggle with Table Schema.

**Comment by peterdesmet** [comment]
Thanks for the suggestion, we'll look into it.

**Comment by peterdesmet** [comment]
We plan to add a new table that can act as an example of the "separate sheet". This table will have the columns:

- column name
- definition
- unit
- required (yes/no)
- controlled values

It will contain a non-exhaustive list of terms

**Comment by peterdesmet** [comment]
A README example table is now included in the document: https://docs.gbif-uat.org/camera-trap-guide/en/#table-readme
