### ISSUE TITLE
Add GBIF extension for Camtrap DP terms

### ISSUE THREAD

**Issue by peterdesmet** [gbif/doc-camera-trap-guide#4]
GBIF created an Asciidoctor extension for terms: https://docs.gbif.org/documentation-guidelines/en/#terms @MattBlissett would it be possible to extend that to Camtrap DP terms?

The syntax might get a bit difficult to implement though, since there is not a single list of terms. That means terms can refer to different pages, for example:

```
created                    | https://tdwg.github.io/camtrap-dp/metadata/#created
taxonomic.taxonid          | https://tdwg.github.io/camtrap-dp/metadata/#taxonomic.taxonid
media-observations.taxonID | https://tdwg.github.io/camtrap-dp/data/#media-observations.taxonID
event-observations.taxonID | https://tdwg.github.io/camtrap-dp/data/#event-observations.taxonID
```

Easier maybe is to implement this using a **reference list** of shortlinks that can be used throughout the whole document, cf. Markdown:

```
[taxonomic.taxonid]: https://tdwg.github.io/camtrap-dp/metadata/#taxonomic.taxonid
[obs.taxonid]: https://tdwg.github.io/camtrap-dp/data/#event-observations.taxonid

Links used in text: Indicate the taxon using a [obs.taxonid] (that is also included in [taxonomic.taxonid])
```

Suggestions welcome.

**Comment by MattBlissett** [comment]
The syntax to include a term link like those coming from the custom extension, but without using that extension, is this:

```asciidoc
link:https://tdwg.github.io/camtrap-dp/metadata/#taxonomic.taxonid[taxonomic.taxonid,role=term]
```

The role (which in HTML becomes a class for the CSS) is specified at the end, and to have this the full `link:` macro needs to be used.

That could be included in a document attribute in index.en.adoc:

```asciidoc
:taxonomic_taxonid: link:https://tdwg.github.io/camtrap-dp/metadata/#taxonomic.taxonid[taxonomic.taxonid,role=term]
```

and then included anywhere in the document with `{taxonomic_taxonid}`.

**Comment by peterdesmet** [comment]
@MattBlissett thanks, I have tried this syntax in e12d28e but it has broken the [build](https://builds.gbif.org/blue/organizations/jenkins/doc-camera-trap-guide/detail/doc-camera-trap-guide/29/pipeline). Can you clarify how I should fix this? Maybe `.` is not allowed in ref names or I've included it at the wrong place in `index.en.adoc`?

**Comment by MattBlissett** [comment]
I think the position in index.en.adoc is OK, but `.` is not allowed — only `A-Za-z0-9` and `_`

**Comment by peterdesmet** [comment]
The build is still failing for `deployments_cameraHeight`: c6123bf3c9c1a9ff63b2836603286aaab01f62c5

**Comment by MattBlissett** [comment]
Ah, then it is unrelated. I upgraded AsciiDoctor-PDF yesterday, and tested many documents but not this one.

**Comment by peterdesmet** [comment]
Ok, I'll wait until you can resolve this.

**Comment by MattBlissett** [comment]
The GBIF extension is now fixed, and the term link in https://docs.gbif-uat.org/camera-trap-guide/en/#camera-height works.

**Comment by peterdesmet** [comment]
Thanks, I've now added all terms.
