### ISSUE TITLE
Review all files in repo

### ISSUE THREAD

**Issue by peterdesmet** [gbif/doc-camera-trap-guide#40]
- [x] 100.en.adoc: keep
- [x] 200.en.adoc: keep
- [x] 300.en.adoc: keep
- [x] 400.en.adoc: keep
- [x] afterword.en.adoc: ~rename acknowledgements.en.adoc~
- [x] bibliography.en.adoc: review
- [x] colophon.en.adoc: review, see #41 
- [x] data/table-01.en.adoc: delete
- [x] glossary.en.adoc: keep
- [x] img/doc-camtrap-illustration.svg: renamed to img/source/camtrap-guide-cover.svg
- [x] img/web/class-diagram.svg: keep
- [x] img/web/deployment-groups.png: keep
- [x] img/web/doc-camtrap-illustration.png: renamed to img/web/camtrap-guide-cover.png
- [x] img/web/example-event-page.png: keep
- [x] img/web/example-image.jpg: keep
- [x] img/web/example-metadata.png: keep
- [x] img/web/photo.jpg: delete
- [x] index.en.adoc: review
- [x] LICENSE.adoc: left untouched
- [x] preface.en.adoc: delete?
- [x] README.adoc: update?
- [x] references.bib: keep

**Comment by peterdesmet** [comment]
@MattBlissett any idea what `<<<` is used for in AsciiDoctor syntax? It is used twice, but I'm not sure it is necessary:

https://github.com/gbif/doc-camera-trap-guide/blob/bbf2b9e6a030fc7bb9c6c9a67b4788f175b214b7/bibliography.en.adoc?plain=1#L5

https://github.com/gbif/doc-camera-trap-guide/blob/bbf2b9e6a030fc7bb9c6c9a67b4788f175b214b7/glossary.en.adoc?plain=1#L118

**Comment by MattBlissett** [comment]
Ungooglable, but it's a page break for the PDF: https://docs.asciidoctor.org/asciidoc/latest/blocks/breaks/
