### ISSUE TITLE
Update colophon

### ISSUE THREAD

**Issue by peterdesmet** [gbif/doc-camera-trap-guide#41]
- [x] Suggested citation: ok
- [x] Authors: ok
- [x] Contributors
- [x] License: ok
- [x] Persistent URI: ok
- [x] Document control: update, see https://github.com/gbif/doc-camera-trap-guide/issues/42
- [x] Abstract: add? cf. https://docs.gbif.org/georeferencing-best-practices/1.0/en/#abstract
- [x] Disclaimer: add? cf. https://docs.gbif.org/georeferencing-best-practices/1.0/en/#disclaimer No disclaimer
- [x] Cover image: add? cf. https://docs.gbif.org/georeferencing-best-practices/1.0/en/#cover-image, no cf. https://docs.gbif.org/publishing-dna-derived-data/en/
- [x] Title at top index.en.adoc

**Comment by peterdesmet** [comment]
@kcopas do you recommend adding a disclaimer cf. georeferencing guide?

> The information in this guide represents the professional opinion of the authors, and does not necessarily represent the views of the publisher. While the authors and the publisher have attempted to make this guide as accurate and as thorough as possible, the information contained herein is provided on an "As Is" basis, and without any warranties with respect to its accuracy or completeness. The authors and the publisher shall have no liability to any person or entity for any loss or damage caused by using the information provided in this guide.

**Comment by kcopas** [comment]
We've done away with doing these kinds of things, to be honest, @peterdesmet. Unless you all are concerned about it, I'd say, no, don't bother.
