### ISSUE TITLE
Publish guide to production

### ISSUE THREAD

**Issue by peterdesmet** [gbif/doc-camera-trap-guide#42]
- [x] Update document status: https://github.com/gbif/doc-camera-trap-guide/blob/25be16608023aff5f562c0d3d003bd55031d854c/colophon.en.adoc?plain=1#L30
- [x] Move from UAT to production

**Comment by kcopas** [comment]
v1.0.0 released and in production. DOI also updated to resolve to production URL. Congrats.

cc @laurarussell @LienReyserhove
