### ISSUE TITLE
Have more control over how citations are displayed

### ISSUE THREAD

**Issue by peterdesmet** [gbif/doc-camera-trap-guide#5]
Hi @MattBlissett, the Georeferencing guide uses the following syntax for references:

```
BioGeomancer project (https://doi.org/10.1371/journal.pbio.0040381[Guralnick et al. 2006^]).

== references

- Guralnick R, Wieczorek J, Beaman R, Hijmans RJ and the Biogeomancer Working Group (2006) BioGeomancer: Automated Georeferencing to Map the World’s Biodiversity Data. PLoS Biology 4(11): e381. https://doi.org/10.1371/journal.pbio.0040381
```

- The user immediately jumps to the article in question when clicking the link, not to the item in the reference list at the bottom of the document
- When the same reference is cited twice, it needs to be maintained separately

---

For this guide we are using the [bibliography](https://docs.asciidoctor.org/asciidoc/latest/sections/bibliography/) guidelines from Asciidoctor. Those make use of triple square brackets to refer to bibliography items:

```
BioGeomancer project (<<ref_guralnick_2006>>).

== References

* [[[ref_guralnick_2006,Guralnick et al. 2006]]] Guralnick R, Wieczorek J, Beaman R, Hijmans RJ and the Biogeomancer Working Group (2006) BioGeomancer: Automated Georeferencing to Map the World’s Biodiversity Data. PLoS Biology 4(11): e381. https://doi.org/10.1371/journal.pbio.0040381
```

Which renders as:

> BioGeomancer project ([[Guralnick et al. 2006]]()).
> 
> ## References
> 
> * [Guralnick et al. 2006] Guralnick R, Wieczorek J, Beaman R, Hijmans RJ and the Biogeomancer Working Group (2006) BioGeomancer: Automated Georeferencing to Map the World’s Biodiversity Data. PLoS Biology 4(11): e381. <https://doi.org/10.1371/journal.pbio.0040381>

A real example can be seen at https://docs.gbif-uat.org/camera-trap-guide/en/#ref_fegraus_2011

This approach has the advantage:

- A reference (especially its doi) only needs to be defined once
- How a reference is displayed `Guralnick et al. 2006` only needs to be defined once

**I was wondering however if you know of a way (syntax, plugin) to provide more control over the display?**

- Don't display the reference in square brackets: `BioGeomancer project (Guralnick et al. 2006)`.
- Allow to use different display formats, such as `BioGeomancer project as described in Guralnick et al. (2006)`.
- Don't repeat the shortname in the references: `* Guralnick R, Wieczorek J, Beaman R, ...`

**Comment by MattBlissett** [comment]
I don't think there's any control over the formatting with the basic built-in method. (See https://docs.asciidoctor.org/asciidoc/latest/sections/bibliography/, they have square brackets etc).

The Asciidoctor-BibTeX plugin is installed, and I demoed it on the Georeferencing document, but we didn't take it any further.  The demo is still deployed: https://github.com/gbif/doc-georeferencing-best-practices/pull/6

**Comment by peterdesmet** [comment]
@kcopas, I discussed this with @laurarussell and we would like to have your input. For citing things in the text, we have 2 options:

## 1. Directly link to DOI or URL

This approach is used for the [Georeferencing Best Practices guide](https://docs.gbif.org/georeferencing-best-practices/1.0/en/).

> Use a data management system like Trapper ([Bubnicki, Churski & Kuijper, 2016](https://doi.org/10.1111/2041-210X.12571)), Agouti (https://agouti.eu) or Wildlife Insights ([Ahumada et al., 2019](https://doi.org/10.1017/S0376892919000298)).

- Advantages: direct link for users + control over formatting.
- Disadvantages: citation is not connected to reference section and thus needs to be maintained twice.

## 2. Using the [asciidoc bibliography format](https://docs.asciidoctor.org/asciidoc/latest/sections/bibliography/)

> Use a data management system like Trapper [[23]](#), Agouti [[3]](#) or Wildlife Insights [[45]](#).

- Advantages: links citation to reference section + interrupts the text less (especially if shown as numbers) + only need to maintain references once.
- Disadvantages: fewer formatting options (displayed text is always going to be wrapped in `[]`) + deviates from typical scientific formatting

**Comment by MattBlissett** [comment]
Did you see the Georeferencing Best Practices example?

The "Apache" in the paragraph "Sources of EPSG codes..." at https://docs.gbif-uat.org/georeferencing-best-practices/with-bibtex-plugin/en/#coordinates-coordinate-reference-system is using the AsciiDoctor BibTeX plugin.

This allows control of formatting and a single place for citations, but it does mean using something that can output BibTeX.

https://github.com/gbif/doc-georeferencing-best-practices/pull/6/commits/528368d18fa75cad6989af8d4fee796298f70761 is the commit demonstrating it, https://github.com/gbif/gbif-asciidoctor-toolkit/blob/master/gbif.csl is the citation style definition.

**Comment by peterdesmet** [comment]
Oh, using BibTex seems like the best approach moving forward, even if that means we have to manually convert our references to that format. I assume they can then be included automatically in the references too, using a specific style definition? Would you be able to set up this repository to make use of that?

**Comment by MattBlissett** [comment]
See https://docs.gbif-uat.org/camera-trap-guide/en/#artificial-intelligence -- I only converted the references used in this paragraph.

You'll need `citenp:[...]` in a few places to avoid the brackets.

**Comment by peterdesmet** [comment]
Looks great! Created issue #12 to tackle conversion.
