### ISSUE TITLE
Glossary terms and chapters

### ISSUE THREAD

**Issue by LienReyserhove** [gbif/doc-camera-trap-guide#6]
When I click on certain terms in the text, they should link to the glossary. However, some terms have their own, equally-named chapter in the guide. So, when I click on the term (e.g. location), I land on the chapter `3.4.2. Location`, rather than on the description of the term in the glossary. 
How should we handle this?

An example in [this paragraph](https://docs.gbif-uat.org/camera-trap-guide/en/#what-are-camera-trap-data) . 

This issue is applicable for the following terms:
- location
- covariates

**Comment by MattBlissett** [comment]
There's a default "anchor" (the bit that shows after `#` when you click these links) for glossary items and chapters.

If they're the same, it's necessary to set a [custom anchor](https://docs.asciidoctor.org/asciidoc/latest/sections/custom-ids/) for either the glossary entry or the chapter.

I suggest changing 

```
==== Location
```

to 

```
[#deployments-location]
==== Location
```

in 300.en.adoc.

**Comment by peterdesmet** [comment]
@LienReyserhove we should discuss on how to best name the chapter anchors.

**Comment by peterdesmet** [comment]
Decided to hardcode all sections with an anchor that starts with `section-`, avoiding name clashes:

```
[#section-deployments]
=== Deployments
```

**Comment by peterdesmet** [comment]
This is now consistently done throughout the document.
