### ISSUE TITLE
How to add figures is asciiDoctor 

### ISSUE THREAD

**Issue by LienReyserhove** [gbif/doc-camera-trap-guide#7]
How can we add figures using asciiDoctor?

**Comment by MattBlissett** [comment]
For photos, screenshots etc then see https://docs.asciidoctor.org/asciidoc/latest/macros/images/

For line/shape diagrams we've tried a few things, and found drawing them using diagrams.net has worked best.  It allows reasonable flexibility for translating the diagrams into other languages.

Example: https://docs.gbif.org/publishing-dna-derived-data/1.0/en/#figure-workflow

and see the note in the Readme for that document: https://github.com/gbif/doc-publishing-dna-derived-data#diagrams

**Comment by peterdesmet** [comment]
Most images added in d0b44b9
