### ISSUE TITLE
More details needed for references

### ISSUE THREAD

**Issue by LienReyserhove** [gbif/doc-camera-trap-guide#8]
For some of the references, I'm not 100% sure which one to add of whether this reference is correct. This is the case for:

- ref_datacite: this is the reference to the participant roles as defined in datacite
- ref_datacite_2015: Darwin Core vocabulary: EML agent role vocabulary. Available from: https://rs.gbif.org/vocabulary/gbif/agent_role.xml [2015-02-13]

For the platforms Wildlife Insights and Agouti, I'm not sure we should include a reference at all, there's no official paper describing the platform, unless I am mistaken

**Comment by LienReyserhove** [comment]
> For some of the references, I'm not 100% sure which one to add. This is the case for:
> 
> * ref_datacite: this is the reference to the participant roles as defined in datacite

**Comment by peterdesmet** [comment]
Those references are now ok in the text. For Agouti and Wildlife Insights we have the best reference available. This can always be updated later if more appropriate citations are available.
