### ISSUE TITLE
Camera trap data, camera-trap data, camera trapping data vs camera-trapping data

### ISSUE THREAD

**Issue by peterdesmet** [gbif/doc-camera-trap-guide#9]
@kcopas, I'm opening this issue since you previously expressed an opinion about this. The camera trap data publishing guide should follow the [United Nations spelling](http://dd.dgacm.org/editorialmanual/ed-guidelines/style/spelling.htm/). I want to know how we can write `camera trap` as an adjective (with or without hyphen).

We recently had a discussion about this for the Camtrap DP manuscript, including when to use camera trap and camera trapping. The arguments by those that participated are are listed below.

**Are you fine if we adopt the same ones for the GBIF guide?**

## TL;DR

1. We consider camera trap and established term, and don't use hyphen for adjectives `camera trap data`
2. We reserve `camera trapping` for the research field (e.g. `camera trapping community`), all the rest is written as `camera trap noun`.

## Breakdown

@peterdesmet 

> I'm no native English speaker, but:
> 
> - When used as a noun, it is without a hyphen: "camera trap"
> - When used as a verb, it is without a hyphen (I believe): "camera trapping"
> - When used as an adjective, it is with a hyphen: "camera-trapping data", "camera-trap data" similar to "large-scale infrastructure" and "low-cost maintenance"
> 
> 1. Can someone confirm these grammatical rules?
> 2. The standard is currently named "Camera Trap Data Package". Should that (grammatically speaking) be "Camera-trap Data Package"?
> 3. In addition, we currently use "camera trapping data/infrastructure/noun" and "camera trap data/infrastructure/noun" interchangeably. Should we be consistent?

@baskaufs

> I will offer an opinion here. I think that the rules you state are applicable in some cases. See [https://www.grammarbook.com/punctuation/hyphens.asp](https://www.google.com/url?q=https://www.grammarbook.com/punctuation/hyphens.asp&sa=D&source=docs&ust=1686663432797693&usg=AOvVaw3TiwlsWDi56xcFNg0iZBpp) for rules about multi-word adjectives. However, applying the hyphen in this case does not seem right to me.
> 
> In most of the examples, we have to glue the words together with hyphens to indicate that we are associating otherwise unrelated words to serve as a compound adjective. However, in this case "camera trap" is already a well-known name for a kind of thing. We don't need to put a hyphen to glue them together. I think if no one had ever used a camera as a kind of "trap" before, we would need the hyphen to indicate that camera is modifying "trap" and that the words belong together.
> 
> This argument seems a bit weaker for "camera trapping", but the hyphen still doesn't seem right to me.
> 
> I suspect that one could make a strong argument for including the hyphens as well, and my argument really is that it just seems awkward to me to include the hyphen. It may be that the editor of whatever journal this is being submitted to will have an opinion and we could just ask them. Probably Gail Kampmeier (BISS editor) would be able to give a better opinion than me if we wanted to ask her.

@danstowell

> My opinion (British English native): Do not include a hyphen.
> 
> Further, I would have expected the title to use the phrase "camera trap data". If you use the "ing" it's less good for SEO, and it also may be slightly confusing since the reader can interpret it as a verb (are we trapping data??)

@peterdesmet / @gkampmeier

> I have asked Gail. There are indeed local differences, but the most important part is being consistent. She falls on the side of not using a hyphen.
> 
> The next decision is where to use "camera trap" vs "camera trapping". Gail writes:
> 
> - camera trap to indicate the equipment (e.g., collecting data via camera trap; setting up camera traps)
> - camera trapping to indicate the action (e.g., we spent the night camera trapping)
> - camera trap research to indicate research/data derived from the equipment, i.e., camera trap
> - camera trapping research to indicate research related to the action of camera trapping. I see this as more philosophical, e.g., do you place the camera at canopy level or above where it may be interfered with by your target organisms? But this also could reflect my lack of experience here (vs. usage by the community).

@peterdesmet 

> I have updated the text to now consistently use "camera trap". "camera trapping" is used for the activity or in combination with "community" and "domain". The full list is:
> 
> camera traps
> camera trap cyber-infrastructure
> camera trap data
> camera trap data analysis
> camera trap data infrastructure
> camera trap data management system
> Camera Trap Data Package
> camera trap data packages
> camera trap data repositories
> camera trap datasets
> camera trap image processing
> Camera Trap Metadata Standard
> camera trap placements
> camera trap project
> camera trap records
> camera trap research teams
> camera trap study
> camera trap videos
> 
> camera trapping
> camera trapping community
> camera trapping domain

**Comment by gkampmeier** [comment]
FYI @peterdesmet the United Nations spelling link was blocked by Sophos in my browser as it detected the presence of malware.

**Comment by kcopas** [comment]
My inclination was indeed to use the hyphenated form for adjectives (leaving aside compound adjectives, like `camera trap-driven`); this ia a matter of diverging opinion and taste, like the Oxford comma. I had had some hope that [National Geographic](https://sites.google.com/a/ngs.org/ngs-style-manual/home) might provide an external source of authority, but no such luck. 

That said, I'm not enough of a zealot to get too exercised about this (like @bauskaufs , I tend to rely on "what seems right to me"). I'm very happy for us to maintain consistency with the (no doubt) hard-won community consensus for representing it in the standard.

fyi, the (updated?) UN spelling guide is https://www.un.org/dgacm/en/content/editorial-manual/spelling.

**Comment by peterdesmet** [comment]
Thanks Kyle!

@gkampmeier Thanks for noticing! I found the link in the GBIF guidelines for authors. I have submitted a PR to change it to the correct one: https://github.com/gbif/doc-documentation-guidelines/pull/21
